language: elixir

sudo: required

services:
  - elasticsearch
  - rabbitmq

os:
  - "linux"

env:
  - CXX=g++-4.8 TRAVIS_NODE_VERSION="6"
  - CXX=g++-4.8 TRAVIS_NODE_VERSION="5"

elixir:
  - 1.3.3
  - 1.3.0

otp_release:
  - 18.2.1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphviz

before_script:
  - "sleep 10"

install:
  - ./.travis/install.sh
  - curl https://sh.rustup.rs -sSf | bash -s -- -y
  - source $HOME/.cargo/env
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
  - mix deps.tree --format dot
  - dot -Tpng deps_tree.dot -o deps_tree.png
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm install
  - npm ls
  - npm run check-updates
  - npm run gulp

script:
   - 'if [ "$TRAVIS_BRANCH" = "docker" ]; then bash .travis/docker-build; fi'

notifications:
  email:
    - korczis@gmail.com
    - lv.bossek@gmail.com
