language: elixir

sudo: required

services:
  - elasticsearch
  - postgresql
  - rabbitmq

os:
  - "linux"

elixir:
  - 1.3.0

otp_release:
  - 18.2.1

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphviz

before_script:
  - "sleep 10"

install:
  - ./.travis/install.sh
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
  - mix deps.tree --format dot
  - dot -Tpng deps_tree.dot -o deps_tree.png
