language: elixir

sudo: required

services:
  - elasticsearch
  - postgresql
  - rabbitmq

os:
  - "linux"

env:
  - CXX=g++-4.8 TRAVIS_NODE_VERSION="6"
  - CXX=g++-4.8 TRAVIS_NODE_VERSION="5"

elixir:
  - 1.3.0
  - 1.2.2

otp_release:
  - 18.2.1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphviz

before_script:
  - "sleep 10"
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres

install:
  - ./.travis/install.sh
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
  - mix deps.tree --format dot
  - mix ecto.create
  - mix ecto.migrate
  - dot -Tpng deps_tree.dot -o deps_tree.png
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - npm ls
  - npm run check-updates
  - npm run gulp

notifications:
  email:
    - korczis@gmail.com
    - lv.bossek@gmail.com
